name: Build Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      working-directory: ./src
      run: make
    - name: make package
      working-directory: ./src
      run: make package
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: cmdb.tar.gz
        path: ./src/bin/pub/cmdb.tar.gz
    - name: Build
      run: |
        echo $PAT | docker login ghcr.io -u 153929962@qq.com --password-stdin
        cp ./src/bin/pub/cmdb.tar.gz ./cmdb.tar.gz
        tar -zxvf ./cmdb.tar.gz
        cd cmdb && ./image.sh -i centos:latest
      env:
        PAT: ${{ secrets.PAT }}
