name: Build Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      working-directory: ./src
      run: make
    - name: make package
      working-directory: ./src
      run: make package
    - uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true
    - name: Build
      run: |
        cp ./src/bin/pub/cmdb.tar.gz ./cmdb.tar.gz
        tar -zxvf ./cmdb.tar.gz
        cd cmdb && ./image.sh -i centos:latest
        docker images
